### ISSUE TITLE
Proposal: Update Project Description

### ISSUE THREAD

**Issue by vinay-s36** [axel358/smartdock#118]
I would like to suggest the following changes to the project description:

**Original**

Very customizable, icons, colors, shapes, sounds
Multi window support
Keyboard shortcuts
Support for both desktop and tablet layouts
Compatible with all Android versions since Nougat, no root required

**New Suggestions**

Highly customizable with options for icons, colors, shapes, and sounds.
Multi-tasking support, including split-screen functionality.
Keyboard shortcuts for improved productivity.
User-friendly interface with support for both desktop and tablet layouts.
Compatibility with Android versions since Nougat, with no root access required

**Comment by dogtopus** [comment]
You can just send a PR for this

**Comment by electrikjesus** [comment]
I think it is good to discuss it first, then submit the PR based on feedback

**Comment by electrikjesus** [comment]
A little feedback: 
- Expand on the Multi-Tasking support and list all available modes
- Mention that it can be run stand-alone or as a launcher
- Mention second-screen functionality

**Comment by vinay-s36** [comment]
@electrikjesus Thanks for the feedback. Here's an updated version of the project description,

Original:

- Very customizable, icons, colors, shapes, sounds
- Multi-window support
- Keyboard shortcuts
- Support for both desktop and tablet layouts
- Compatible with all Android versions since Nougat, no root required

Revised:

- Highly customizable with extensive options for icons, colors, shapes, and sounds.
- Comprehensive multi-tasking support, including split-screen, floating window, and picture-in-picture modes.
- Productivity-enhancing keyboard shortcuts for seamless navigation.
- User-friendly interface adaptable for both desktop and tablet layouts.
- Full compatibility with Android versions since Nougat, without requiring root access.

Updated with your feedback:

- Can be used as a standalone application or as a feature-rich launcher.
- Unique second-screen functionality for enhanced multitasking and productivity.

If you have any more feedback or further changes please let me know I'll make adjustments accordingly.

**Comment by electrikjesus** [comment]
With the line: "Comprehensive multi-tasking support, including split-screen, floating window, and picture-in-picture modes.", I feel that is misleading as to what Smart-Dock enables the user to do as those are just options that come with Android by default. We should list the multitasking modes that SD allows the user to launch apps instead (Open In > Standard, Maximized, Portrait, Fullscreen) along with maybe a thumbnail screenshot of an app in each mode for reference

**Comment by electrikjesus** [comment]
We could also highlight some of the features in the app, like the App Drawer, describing more of it's features and functions. The Taskbar, and the notification drawer as well

**Comment by vinay-s36** [comment]
i will look into this

**Comment by electrikjesus** [comment]
We could split the effort into a few separate changes too. One for the main wording, and another with the image assets and deeper dive into the options in Settings.

**Comment by axel358** [comment]
> @electrikjesus Thanks for the feedback. Here's an updated version of the project description,
> 
> Original:
> 
> * Very customizable, icons, colors, shapes, sounds
> * Multi-window support
> * Keyboard shortcuts
> * Support for both desktop and tablet layouts
> * Compatible with all Android versions since Nougat, no root required
> 
> Revised:
> 
> * Highly customizable with extensive options for icons, colors, shapes, and sounds.
> * Comprehensive multi-tasking support, including split-screen, floating window, and picture-in-picture modes.
> * Productivity-enhancing keyboard shortcuts for seamless navigation.
> * User-friendly interface adaptable for both desktop and tablet layouts.
> * Full compatibility with Android versions since Nougat, without requiring root access.
> 
> Updated with your feedback:
> 
> * Can be used as a standalone application or as a feature-rich launcher.
> * Unique second-screen functionality for enhanced multitasking and productivity.
> 
> If you have any more feedback or further changes please let me know I'll make adjustments accordingly.

Remove the picture in picture mode part as well as the second screen feature, we're not there yet. Feel free to send a PR any time and thank you for your contribution :)
