### ISSUE TITLE
Option to show soft keyboard when the apps menu opens

### ISSUE THREAD

**Issue by naranyala** [axel358/smartdock#122]
I thought it was kind of neat to have option when launch the "App Menu" either autofocus on the search bar or not. 

in my case it didn't trigger the keyboard to display.

**Comment by axel358** [comment]
Hi there this has been fixed on main. Grab the latest build from the Actions tab and try it. Feel free to reopen the issue if it's not working as expected

**Comment by axel358** [comment]
Had to revert the fix since it causes issues for desktop users. For now one more tap is needed to bring up the soft keyboard

**Comment by KeronCyst** [comment]
> one more tap

Yes, but the tap is all the way at the top of the screen (kinda like the Play Store's absurd search engine UI change). It'd be nice if the search bar was at least at the bottom, right where the keyboard will be.
