### ISSUE TITLE
"Kotlin branch" Bug report.

### ISSUE THREAD

**Issue by krrishkap** [axel358/smartdock#126]
Crash log attached it crashes instantly after clicking on "default apps" in smartdock settings . 
Apps are not getting pinned automatically after opening them in windowed mode , double checked all the related settings on my end but it just doesn't work. Everything else is working perfectly. UI is smooth af .
Edit: Forgot to mention the app crash when kept on lockscreen also got fixed .

[crash_log_2024-01-10_22-43-07.log](https://github.com/axel358/smartdock/files/13890949/crash_log_2024-01-10_22-43-07.log)

**Comment by axel358** [comment]
@krrishkap Thanks champ
