### ISSUE TITLE
Bug: Autohide setting is forgotten

### ISSUE THREAD

**Issue by CM630** [axel358/smartdock#130]
The autohide setting is continually forgotten.
When it is enabled the PIN icon gets striken-trough, the taskbar gets autohidden.
After some time the taskbar stops autohiding, the PIN is not striken-trough anymore.

Observed on Android 10; X96Q TV box; Installed from F-Droid (Version should be 1.11.0).

**Comment by CM630** [comment]
@axel358 
I just launch the app. How to find what mode I am using?

**Comment by axel358** [comment]
@CM630 The default launch mode on phones is full screen, the dock unpins on full screen apps by default. U can configure this behavior in Dock/Auto pin/unpin on full screen apps

**Comment by CM630** [comment]
Most likely the mode was „Desktop“.
I have uninstalled smartdock because of this and some other issues, so I tries to reinstall now.
But when I try to set the overlay permissions I get:
![image](https://github.com/axel358/smartdock/assets/15823107/2f6c5200-c516-4a25-9d07-0c14de5894c2)
