### ISSUE TITLE
App crashes when opening app menu

### ISSUE THREAD

**Issue by AMZBoss215** [axel358/smartdock#146]
Using the app for a while. One day, when I simply clocked the app menu icon, instead of opening, it just crashed and then displayed the following error:

![Screenshot_20240315-214715](https://github.com/axel358/smartdock/assets/145992643/007da8c4-63ec-4803-be02-5b6d793dfef0)
![Screenshot_20240315-214706](https://github.com/axel358/smartdock/assets/145992643/429a89c5-b4cc-4835-8b51-9d51b5bc00de)

**Comment by axel358** [comment]
Clean the app data. Seems like you upgraded from fdroid without reading the release notes

**Comment by AMZBoss215** [comment]
The release notes were not as explicit as what I understood, I resolved this by uninstalling and reinstalling
