### ISSUE TITLE
Restore not working 

### ISSUE THREAD

**Issue by katastrophe92** [axel358/smartdock#148]
Tried to restore the settings and got this error message. Save the logs button didn't worked also that's why the screenshots. 

One more question. Could you upload the final release APK to GitHub? I use Obtainiun app to install and update my apps. 

![SmartSelect_20240321_003922_Smart Dock.jpg](https://github.com/axel358/smartdock/assets/103950507/4eda17c3-a5d5-43d6-8d8e-b38de6179b53)

![SmartSelect_20240321_004100_Smart Dock.jpg](https://github.com/axel358/smartdock/assets/103950507/b776841f-707d-4c7e-9e60-de8058c89bf1)

![SmartSelect_20240321_003952_Smart Dock.jpg](https://github.![SmartSelect_20240321_004025_Smart Dock.jpg](https://github.com/axel358/smartdock/assets/103950507/e5c0c5c1-8547-4098-81dc-e30be059a485)

a-782ca5914a7f)

![Uploading SmartSelect_20240321_004025_Smart Dock.jpg …]()

**Comment by axel358** [comment]
hi there thank u for reporting the problem. It has been fixed here [575a1ce](https://github.com/axel358/smartdock/commit/575a1ce4eecc79ce2ca8bb96f8e8e818c2c1e375). Try an apk from the actions tab n see if it's all good for u, if it's not feel free to reopen the issue. About the releases yes i think i could attach the apk as well
