### ISSUE TITLE
Problem Smartdock 

### ISSUE THREAD

**Issue by SKAT819** [axel358/smartdock#150]
Floating problem currently Android 12![Screenshot_20240327-213420](https://github.com/axel358/smartdock/assets/126221316/07466dd4-7a05-4c43-b63c-2287e7ef3125)
![Screenshot_20240327-213422](https://github.com/axel358/smartdock/assets/126221316/6d50a31f-78b0-40e9-bb35-3d927cdf6632)

**Comment by SKAT819** [comment]
Resolved

**Comment by SKAT819** [comment]
The problem here is the app menu button

**Comment by axel358** [comment]
Clear the app's data
