### ISSUE TITLE
[FR] Allow selecting any screen edge for Smart Dock to use

### ISSUE THREAD

**Issue by doqfgc** [axel358/smartdock#151]
Currently Smart Dock is designed with only the bottom edge as the only useable screen edge. This is fine in a majority of cases, but some people (such as myself) would prefer a different screen edge. I would use this way more if I could set the dock to pop from, say, the right edge.

**Comment by axel358** [comment]
I'm willing to merge a PR for this but it's not something I have the time to work on myself. Allowing changing the screen edge requires changing how we position views, calculate free screen space etc
