### ISSUE TITLE
(not a issue) Updating without a app store

### ISSUE THREAD

**Issue by katastrophe92** [axel358/smartdock#152]
First of all thank you for this amazing repository, I really LOVE IT. Thanks!

Would you please add the .APK to the releases in order to be able to update through [Obtainium](https://github.com/ImranR98/Obtainium). It is way safer, easier to restore all Open Source apps. Awesome app
The last attached .APK in the releases was the first SmartDock version

**Comment by JoshAtticus** [comment]
You can add F-Droid apps to Obtainium
