### ISSUE TITLE
Smart Dock MD5 mismatch

### ISSUE THREAD

**Issue by atirut-w** [axel358/smartdock#156]
The script gets stuck in a loop trying to redownload and failing from MD5 mismatches.

```
$ sudo venv/bin/python3 main.py install smartdock
INFO: Downloading smartdock.apk now to /home/atirut/.cache/waydroid-script/downloads/smartdock.apk .....
14.7kiB [00:00, 21.6MiB/s]
WARN: md5 mismatches, redownloading now ....
14.7kiB [00:00, 23.3MiB/s]
WARN: md5 mismatches, redownloading now ....
```

**Comment by Ardya2189** [comment]
how to fix it?

**Comment by KSMaan45** [comment]
@Ardya2189 thats not official smartdock script, so download smartdock manually from fdroid or use this script for waydroid https://github.com/electrikjesus/wd-scripts/blob/main/add-smart-dock.sh
