### ISSUE TITLE
Showing a 2 sign on app icons on dock

### ISSUE THREAD

**Issue by KamrulShahed** [axel358/smartdock#159]
I dont know whether its a feature or issue but for me its a great issue. Randon 2 sign appears on top left of the icons in dock. The issue is i cant open the app that shows this sign. When i click on the icon it shows same two instance of the same appname and icon but does nothing when i click on them. They appears randomly on app icons. Sometimes opening another app makes a sign of another app disappear or somtimes the just shifts from one to another icon. Now they are appearing on 8 of my icons out of 12 and i cant access them from dock. Its becoming unusable. I noticed (just a guess) it happens most when i use more than 10 recent apps in dock and pin some of them. It doesn't mean they appear only on pined ones. They looks like notification badges on launchers. I dont know if they show 2 instances of same app. But they should be openable at least. I still dont know the reason behind their appearing and disappearing but they are bothering a lot. It became almost unusable.

**Comment by axel358** [comment]
Solved by a2bac247069b9a6b26a034b38b1e31d8fed4cdc0
