### ISSUE TITLE
Please provide this via F-Droid.

### ISSUE THREAD

**Issue by rokejulianlockhart** [axel358/smartdock#16]
My rationale is available at https://github.com/Tadashi-Hikari/Sapphire/issues/2#issue-1228766021.

(Separated from https://github.com/axel358/smartdock/issues/13#issuecomment-1426918492.)

**Comment by axel358** [comment]
Almost there ;)

**Comment by axel358** [comment]
https://f-droid.org/packages/cu.axel.smartdock/
:)

**Comment by axel358** [comment]
https://f-droid.org/packages/cu.axel.smartdock/
:)

**Comment by rokejulianlockhart** [comment]
Thanks, @axel358.
