### ISSUE TITLE
[Feature request] load smart dock on external display only (desktop mode)

### ISSUE THREAD

**Issue by MastaG** [axel358/smartdock#160]
Android has a limitation where you can only set a single home screen launcher.
You cannot choose one for use with external displays only.

Taskbar (another app) has an option to select the default launcher (e.g. trebutched, crdroid home, google launcher).
This will be chainloaded when you don't want the dock to be active.
So when you set taskbar as the default home screen launcher,  you can configure it to load your default launcher for your phone's display and only show the dock when an external display is connected.
Kind of like how Dex works.

**Comment by axel358** [comment]
We can track this along with #35
