### ISSUE TITLE
Have you planned to support multi-languages?

### ISSUE THREAD

**Issue by 1457384613gh** [axel358/smartdock#17]
Have you planned to support multi-languages?
I am ready to help to translate its UI into other languages.
If having planned, give me a way to translate.

**Comment by axel358** [comment]
@1457384613gh Sure, what language(s) would u be willing to translate to?

**Comment by axel358** [comment]
@1457384613gh https://github.com/axel358/smartdock/blob/main/app/src/main/res/values/strings.xml

Translate this file and place your translation on a folder under https://github.com/axel358/smartdock/blob/main/app/src/main/res named values-{lang code} where lang code for example spanish translations go in a folder called values-es https://github.com/axel358/smartdock/blob/main/app/src/main/res/values-es/strings.xml

**Comment by ilhan-athn7** [comment]
@1457384613gh As you wish,

Pull requests are welcome, see examples here;
https://github.com/axel358/smartdock/pulls?q=is%3Apr+is%3Aclosed

**Comment by Xtr126** [comment]
> Another question.
> Can I add comments with `#`?

In shell scripts you comment code with `#` but not everywhere.
Use the menu option / keyboard shortcut or whatever your IDE provides to comment code. Refer documentation. 
This is how you are supposed to add comments in .xml 
```xml
<string name="hello">Hello</string>
  <!-- comment here -->
<string name="bye">Bye</string>
```
And block comments: 
```xml
<string name="me">Me</string>
<!-- 
 lines of 
 text  -->
<string name="you">You</string>
```
