### ISSUE TITLE
Be able to keep dock persistent after picking an app

### ISSUE THREAD

**Issue by KeronCyst** [axel358/smartdock#175]
**EDIT:** To clarify, I don't know what the pin button does, because on my Samsung S21 FE on Android 12, the pin icon always slashes itself upon choosing an app and then retracts the dock.

This app is great, and I further envision it being able to partly replace the homescreen by having full apps in the list for instant, one-touch multitasking. However, we currently have to keep revealing the dock after app-switching because it hides itself.

Can we have an option to make it never hide itself on its own?

**Comment by axel358** [comment]
Settings>Dock>Auto pin

**Comment by KeronCyst** [comment]
That isn't working, though; it still retracts itself after touching an app.
