### ISSUE TITLE
Requesting snappier response when swiping up/down to tuck/show

### ISSUE THREAD

**Issue by KeronCyst** [axel358/smartdock#177]
It'd be great if the dock raised/lowered immediately with your finger as you swipe, while it's still touching the screen. Sometimes I'm not sure if it took effect, and there also appears to be quite a relative delay before it moves at all; I'm hoping this delay can be reduced.

**Comment by axel358** [comment]
The delay is caused by the show/hide animation

**Comment by KeronCyst** [comment]
Thanks, but where can I find this? I wish there was a search engine in the settings so I could just run a query for "anim" and pull it up.
