### ISSUE TITLE
Taskbar hides the bottom of apps

### ISSUE THREAD

**Issue by AndronikosGl** [axel358/smartdock#181]
When i open an app i want its size to be above the taskbar because some apps have bottom bar controls and the taskbar is hiding then

**Comment by axel358** [comment]
There's no way to tell the system to reserve space for Smart Dock as it does for the navigation buttons. If you're using Android 12+ with navigation buttons smart dock will draw on top of them, for previous versions there's no workaround

**Comment by realyukii** [comment]
Can I make Smart Dock to hide until I hover it? (like the Windows taskbar)

I tried take a look at this [README](https://github.com/axel358/smartdock/blob/main/HideNav.md), however, even after reboot it didn't work as expected (as described above) and thus the behaviour of taskbar hides the bottom of apps is still persist

> There's no way to tell the system to reserve space for Smart Dock as it does for the navigation buttons. If you're using Android 12+ with navigation buttons smart dock will draw on top of them, for previous versions there's no workaround

I use BlissOS Android 13, but I'm not sure how to use `navigation buttons smart dock`?
