### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [axel358/smartdock#34]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

**Comment by axel358** [comment]
Github discussions as far as I'm aware require an organization and we already have a Telegram group linked in the readme

**Comment by rokejulianlockhart** [comment]
@axel358, they shouldn't require an organization – I'm confident that my (@rokejulianlockhart)'s https://github.com/rokejulianlockhart?tab=repositories&type=source use them too.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/axel358/smartdock/issues/34#issuecomment-1556320901

@axel358, they appear to be possible to enable at an organisation-wide *or* repository-wide level. It might be mutually exclusive; not that that matters here.
