### ISSUE TITLE
A toggle to disable pop-up notifications

### ISSUE THREAD

**Issue by gaussandhisgun** [axel358/smartdock#50]
I like the bottom aligned notification panel, comes handy in the moments when my system status bar is hidden. But I don't want to see SmartDock's pop-up notifications, ant currently the only ways to disable them are either manually blacklisting every app that can send notifications or disabling notification service; which one is long and hacky and the other gets rid of bottom notification panel. I think adding a few extra `if`-s and a toggle in Settings (and/or inside the notification panel itself) should not be that hard to do.

**Comment by axel358** [comment]
![dnd](https://github.com/axel358/smartdock/assets/72220889/041b13c8-5e16-4cfb-9976-94a0bb78e550)

Added in the next version
