### ISSUE TITLE
miui don't let me change launcher

### ISSUE THREAD

**Issue by VanTuz5** [axel358/smartdock#52]
How to install this launcher if miui 14 does not allow you to change it?

**Comment by axel358** [comment]
@VanTuz5 Try setting it from system settings > Home app

**Comment by VanTuz5** [comment]
Don't work. miui writes that third-party applications can cause memory leaks and the like, so you can only install what miui checked itself

**Comment by VanTuz5** [comment]
The problem is solved - in the same menu where permissions are issued, there is an item below, I don’t remember the name, but something about the screen. And there you can choose this launcher instead of miui.
