### ISSUE TITLE
Can't enable accessibility service and notification service for the app

### ISSUE THREAD

**Issue by KanZyy** [axel358/smartdock#56]
The app is greyed out and didn't found ANY way to work around that problem...
(Device: Nothing Phone (1) -  Android 13)
Is there anything I can do in the developer option?

**Comment by KanZyy** [comment]
![Screenshot_20230621-074713](https://github.com/axel358/smartdock/assets/94768324/fea48adc-e0d1-4d8f-9fbc-16357a69fdaf)
![Screenshot_20230621-074726](https://github.com/axel358/smartdock/assets/94768324/51b691f7-8fa0-4a8e-8e83-b1307f5dcaf2)

**Comment by ilhan-athn7** [comment]
Settings > Apps > Smartdock > 3 Dot menu (Top right corner) > Allow restricted permissions

**Comment by KanZyy** [comment]
> Settings > Apps > Smartdock > 3 Dot menu (Top right corner) > Allow restricted permissions

Thanks!
