### ISSUE TITLE
Is there any way to make the dock float like A13 if not is it possible

### ISSUE THREAD

**Issue by SeanDylan** [axel358/smartdock#58]
It would be nice if it was like this it takes out less space and i could use any bottom shortcuts on any app

**Comment by axel358** [comment]
Could you describe your request a bit more? What do you mean by bottom shortcuts on any app?

**Comment by SeanDylan** [comment]
> Could you describe your request a bit more? What do you mean by bottom shortcuts on any app?

I meant that there should be an option for a floating dock just like the pixel tablet and fold basically it might clear up some space for bottom up bars if you cannot use them

**Comment by axel358** [comment]
The dock automatically hides when launching apps in full screen by default, there is no way to make the system reserve space for it like it does for the nav bar buttons

**Comment by novafurry** [comment]
Ive just seen this again, and found an image which is what i think OP was talking about

![image](https://github.com/user-attachments/assets/e6e612f8-5273-4456-89c2-45b242b22a93)
see the dock at the bottom that can be seen on android 13+ tablets?

**Comment by P0bo** [comment]
I would really love if the app adds this . I have tried installing the Google pixel rom for this but my device isn't supported.

https://github.com/user-attachments/assets/83672cef-3e16-4b2a-8021-e827c645994d
