### ISSUE TITLE
Allow screen rotation

### ISSUE THREAD

**Issue by Kabouik** [axel358/smartdock#67]
I recently started to use Smartdock on my Droidian phone using Waydroid and am happy with it. However, since it forces landscape on the Lineage system within Waydroid, all apps are also forced to landscape, and for some this a broken orientation that makes them unusable (buttons out of the screen). Of course landscape is what I want with Smartdock, but I would like to be able to temporarily rotate the whole Lineage system or just some apps.

Even rotation-control apps had no effect while Smartdock is used. Re-enabling Trebuchet as my launcher without removing Smartdock didn't work either. I observed the same whether I start Waydroid while my host OS (Droidian) is rotated to landscape or portrait, no change (while, before Smartdock, it would change the default orientation of Lineage).

Is there a way to do that? I'm sure other users have had trouble with some apps made unusable by the landscape orientation.

**Comment by axel358** [comment]
@Kabouik Tried the rotation quick settings on SD notification panel

**Comment by Kabouik** [comment]
Thanks, I had no idea the setting was hidden there and overriding the usual toggle in Android top menu (that is what I tried). I can now start Smartdock in portrait indeed, as long as I start Waydroid in portrait too. Perfect!
