### ISSUE TITLE
App hiding 

### ISSUE THREAD

**Issue by JayKx** [axel358/smartdock#69]
App hiding should be added. Its crucial feature on most launchers today. Since we rely on a home screen which is very condensed, we should have the option to hide unused apps. Thus clearing the clutter. Also there should be easier to access them as well, say by searching them explicitly.

**Comment by 0xlne** [comment]
I second that request; I have a bunch of apps which are unneeded in my drawer; either stock duplicates, or from managed profiles. It's just taking up space & being visual noise.
