### ISSUE TITLE
App menu slow

### ISSUE THREAD

**Issue by owencz1998** [axel358/smartdock#85]
Loading app menu is slow

**Comment by axel358** [comment]
@owencz1998 Care to try the latest build from the actions tab or the telegram group?

**Comment by owencz1998** [comment]
OK mate thank you

**Comment by axel358** [comment]
Also please use labels, for example instead of [Bug] use the Bug label

**Comment by owencz1998** [comment]
Ahh didn't see them due to using app github haha my bad also its quicker than before but no way to swipe up and down to open app menu also is there away to fix this mate



 ![Screenshot_20230829_210951_Smart Dock.jpg](https://github.com/axel358/smartdock/assets/96526481/a53f44fd-2827-4007-aee2-a6431a022f8d)

**Comment by owencz1998** [comment]
I wouldn't say the response is good at the moment mate
