### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by XODE871** [axel358/smartdock#9]
![IMG_20220717_175430](https://user-images.githubusercontent.com/107128905/179398305-b4aec735-ea89-4608-bb82-adca97bd7969.jpg)

Please fix this error !!!

**Comment by axel358** [comment]
@XODE871 He didn't even described his issue

**Comment by axel358** [comment]
Could you please provide more information. When does it happen? Which app version are you using?

**Comment by XODE871** [comment]
> Could you please provide more information. When does it happen? Which app version are you using?

When I gave it the acc

**Comment by axel358** [comment]
@XODE871 I need:
Android distro and version u're using
Does the crash happen often?
Where did u get the app from?
App version

**Comment by MrMiy4mo** [comment]
Primeos have problem with accesibility service apps that are known to have keyevent listener.

We told about that problem to primeos team, it seems that they dont prioritize this issue for now.

**Comment by rokejulianlockhart** [comment]
@ilhan-athn7, do you have a link to the report?

**Comment by ilhan-athn7** [comment]
Nope, they collect reports via google forms.
They focused on primebook and have no progress for x86 platform.

**Comment by axel358** [comment]
This is a Prime OS issue, not ours
