### ISSUE TITLE
Other communication channels than Telegram

### ISSUE THREAD

**Issue by testman42** [axel358/smartdock#93]
Would you be willing to come join some communication platforms other than Telegram?
Community around Smartdock would grow much more on platforms that do not require telephone number.
I can set up a Matrix room, if you are interested.

**Comment by axel358** [comment]
I use Telegram for a lot of things, work, mail, projects i follow, github notifications, friends, family. Since my free time is limited its nice to have it all accessible on a single place. We could do a Matrix room, but i wouldn't be able to be as active as i am on Telegram
